### ISSUE TITLE
Exponentially Decreasing Attention?

### ISSUE THREAD

**Issue by ansonkao** [tfernd/HyperTile#2]
Just a thought. Have you considered or tried some sort of variation where the attention still covers the entire image, but at lower granularity the further away it is from the target pixel?

Just thinking that this is how the human attention works, and perhaps it could be the best of both worlds between your current tiled attention approach and full attention

**Comment by tfernd** [comment]
Yes, I have thought about it. Unfortunately we would have to aggregate the tiles somehow, to have a pixel to tile attention out-side its scope. And ToMe has show that aggregation make images bad and LoRAs behave weirdly... And It would require to compute the score matrix and reasembling things before fixing the tiles. It's messy. I tried.
Seems way easier to just restrict global attention altogether. And it works.
